export default function Head() {
  return (
    <>
      {/* Before first paint: restore the persisted package-manager choice (see styles.css). */}
      <script
        dangerouslySetInnerHTML={{
          __html:
            "try{var p=localStorage.getItem('pm');document.documentElement.dataset.pm=p==='pnpm'||p==='bun'||p==='yarn'?p:'npm'}catch(e){document.documentElement.dataset.pm='npm'}",
        }}
      />
      <meta property="og:url" content="https://the-framework.ai/" />
      <meta property="og:type" content="website" />
      {/* Generated by screenshotting /banner — see the Banner section on /press. */}
      <meta property="og:image" content="https://the-framework.ai/banner.jpg" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link
        href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap"
        rel="stylesheet"
      />
    </>
  )
}
